on:
  workflow_dispatch:
    inputs:
      iteration:
        description: 'Iteration to move issues from'
        required: false
        default: 'current'
      new-iteration:
        description: 'Iteration to move issues to'
        required: false
        default: 'next'
  schedule:
    # Runs "at 18:00 JST, only on Friday"
    - cron: '0 9 * * 5'

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest
    env:
      PROJECT_NUMBER: 3
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set iteration values
      run: |
        echo "iteration=${{ github.event.inputs.iteration || 'current' }}" >> $GITHUB_ENV
        echo "new_iteration=${{ github.event.inputs.new-iteration || 'next' }}" >> $GITHUB_ENV

    - name: Check and create next iteration if necessary
      env:
        GH_TOKEN: ${{ secrets.PROJECT_PAT }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        chmod +x ./scripts/move-to-next-iteration/create_next_iteration.sh
        ./scripts/move-to-next-iteration/create_next_iteration.sh $PROJECT_NUMBER

    - uses: blombard/move-to-next-iteration@master
      with:
        owner: ${{ github.repository_owner }}
        number: $PROJECT_NUMBER
        token: ${{ secrets.PROJECT_PAT }}
        iteration-field: Iteration
        iteration: ${{ env.iteration }}
        new-iteration: ${{ env.new_iteration }}
        statuses: 'Backlog,In progress,In review'